Repository fga-eps-mds/2020.1-eSaudeUnB-FrontEnd, pull requests merged in 2020-11, with the labels that each got.

#16 Landing Page
  src/assets/images/wave.svg
  src/assets/styles/FaqCard.css
  src/assets/styles/HiwCard.css
  src/assets/styles/LandingNavBar.css
  src/components/LandingNavBar.js
  src/pages/Landing/index.js
  src/pages/Landing/styles.css
  src/pages/NewSession/styles.css
  src/pages/PatientRecord/styles.css
Labels: enhancement

#18 Feature/user appointment
  package-lock.json
  src/components/NavBar.js
  src/pages/LandingLogin/index.js
  src/pages/PsychologistEvents/index.js
  src/pages/PsychologistEvents/styles.css
  src/pages/PsychologistSchedule/index.js
  src/pages/UserEvents/index.js
  src/pages/UserEvents/styles.css
  src/pages/UserMain/index.js
  src/pages/UserMain/styles.css
  src/pages/UserSchedule/index.js
  src/pages/UserSchedule/styles.css
  src/routes.js
Labels: enhancement

#19 Fix/front repairs
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/assets/images/arrow.svg
  src/assets/images/up.svg
  src/assets/images/userIcon.svg
  src/assets/styles/Loader.css
  src/assets/styles/NavBar.css
  src/assets/styles/SearchBar.css
  src/assets/styles/SideBar.css
  src/components/Loader.js
  src/components/Logo.js
  src/components/NavBar.js
  src/components/SearchBar.js
  src/components/SideBar.js
  src/pages/LandingLogin/index.js
  src/pages/LandingLogin/styles.css
  src/pages/LandingSignUp/index.js
  src/pages/LandingSignUp/styles.css
  src/pages/LoginAdmin/index.js
  src/pages/LoginAdmin/styles.css
  src/pages/PatientList/index.js
  src/pages/PatientList/styles.css
  src/pages/PsychologistCalendar/index.js
  src/pages/PsychologistCalendar/styles.css
  src/pages/PsychologistCreate/index.js
  src/pages/PsychologistCreate/styles.css
  src/pages/PsychologistList/index.js
  src/pages/PsychologistList/styles.css
  src/pages/PsychologistProfile/index.js
  src/pages/PsychologistProfile/styles.css
  src/pages/PsychologistSchedule/styles.css
  src/pages/UserMain/index.js
  src/pages/UserProfile/index.js
  src/pages/UserProfile/styles.css
Labels: enhancement

#22 Bugfix/component correction
  src/pages/PsychologistEvents/index.js
  src/pages/PsychologistSchedule/index.js
  src/pages/UserMain/index.js
Labels: bug

#24 Responsive designer
  src/assets/styles/LandingNavBar.css
  src/assets/styles/NavBar.css
  src/components/LandingNavBar.js
  src/components/Logo.js
  src/components/NavBar.js
  src/components/SideBar.js
  src/pages/Landing/index.js
  src/pages/Landing/styles.css
  src/pages/LandingLogin/styles.css
  src/pages/LandingSignUp/index.js
  src/pages/LandingSignUp/styles.css
  src/pages/NewSession/index.js
  src/pages/NewSession/styles.css
  src/pages/PatientList/index.js
  src/pages/PatientRecord/index.js
  src/pages/PatientRecord/styles.css
  src/pages/PsychologistCalendar/index.js
  src/pages/PsychologistList/index.js
  src/pages/PsychologistProfile/styles.css
  src/pages/UserProfile/styles.css
Labels: enhancement, help wanted

#21 Update password
  src/pages/PsychologistProfile/index.js
  src/pages/UserMain/index.js
  src/pages/UserProfile/index.js
  src/pages/UserProfile/styles.css
Labels: enhancement

#20 Waiting List
  src/pages/PsychologistEvents/index.js
  src/pages/UserEvents/index.js
  src/pages/UserMain/index.js
  src/pages/UserMain/styles.css
  src/pages/UserSchedule/index.js
  src/pages/WaitingList/index.js
  src/pages/WaitingList/styles.css
  src/routes.js
Labels: enhancement

#27 User Infos
  src/components/NavBar.js
  src/pages/LandingLogin/index.js
  src/pages/PsychologistProfile/styles.css
  src/pages/UserProfile/index.js
  src/pages/UserProfile/styles.css
Labels: enhancement
