Repository fga-eps-mds/2020.1-eSaudeUnB-FrontEnd, pull requests merged in 2020-12, with the labels that each got.

#30 Feature/responsive platform
  src/assets/styles/Calendar.css
  src/components/Logo.js
  src/components/NavBar.js
  src/components/SideBar.js
  src/pages/AdminMain/styles.css
  src/pages/LandingLogin/index.js
  src/pages/LandingLogin/styles.css
  src/pages/LandingSignUp/styles.css
  src/pages/LoginAdmin/styles.css
  src/pages/PatientList/styles.css
  src/pages/PsychologistCalendar/index.js
  src/pages/PsychologistCalendar/styles.css
  src/pages/PsychologistCreate/index.js
  src/pages/PsychologistCreate/styles.css
  src/pages/PsychologistEvents/index.js
  src/pages/PsychologistEvents/styles.css
  src/pages/PsychologistList/styles.css
  src/pages/PsychologistSchedule/index.js
  src/pages/PsychologistSchedule/styles.css
  src/pages/UserEvents/index.js
  src/pages/UserEvents/styles.css
  src/pages/UserMain/index.js
  src/pages/UserMain/styles.css
  src/pages/UserProfile/index.js
  src/pages/UserProfile/styles.css
  src/pages/UserSchedule/index.js
  src/pages/UserSchedule/styles.css
Labels: enhancement

#31 Feature/forget password
  package-lock.json
  src/pages/ChangePassword/index.js
  src/pages/ChangePassword/styles.css
  src/pages/LandingLogin/index.js
  src/pages/LandingLogin/styles.css
  src/routes.js
  yarn.lock
Labels: enhancement

#32 Feature/schedule
  package-lock.json
  src/pages/PsychologistCalendar/index.js
  src/pages/PsychologistCalendar/styles.css
  src/pages/PsychologistSchedule/index.js
Labels: enhancement

#36 Feature tests front
  Makefile
  package-lock.json
  package.json
  src/components/Menu/Menu.js
  src/components/Menu/styles.css
  src/setupTests.js
  src/tests/AdminMain.test.js
  src/tests/LandingLogin.test.js
  src/tests/LandingSignUp.test.js
  src/tests/LoginAdmin.test.js
  src/tests/NewSession.test.js
  src/tests/NotFound.test.js
  src/tests/PatientList.test.js
  src/tests/PatientRecord.test.js
  src/tests/PsychologistCalendar.test.js
  src/tests/PsychologistCreate.test.js
  src/tests/PsychologistEvents.test.js
  src/tests/PsychologistList.test.js
  src/tests/PsychologistProfile.test.js
  src/tests/PsychologistSchedule.test.js
  src/tests/UserEvents.test.js
  src/tests/UserMain.test.js
  src/tests/UserProfile.test.js
  src/tests/UserSchedule.test.js
  src/tests/WaitingList.test.js
  src/tests/footer.test.js
  src/tests/input.test.js
  src/tests/landing.test.js
  src/tests/landingNavBar.test.js
  src/tests/loader.test.js
  src/tests/logo.test.js
  src/tests/navbar.test.js
  src/tests/realizeSearch.test.js
  src/tests/searchBar.test.js
  src/tests/searchedPatients.test.js
  src/tests/sidebar.test.js
Labels: enhancement

#34 Fix/improvement pages
  package-lock.json
  package.json
  src/pages/NewSession/index.js
  src/pages/NewSession/styles.css
  src/pages/PatientRecord/index.js
  src/pages/UserProfile/index.js
  src/pages/UserProfile/styles.css
  src/tests/LandingLogin.test.js
  yarn.lock
Labels: enhancement

#40 Bugfix
  src/components/NavBar.js
  src/components/SearchBar.js
  src/components/SideBar.js
  src/pages/AdminMain/index.js
  src/pages/AdminMain/styles.css
  src/pages/LandingLogin/index.js
  src/pages/LandingLogin/styles.css
  src/pages/NewSession/index.js
  src/pages/PatientRecord/index.js
  src/pages/PsychologistCalendar/index.js
  src/pages/PsychologistCreate/index.js
  src/pages/PsychologistEvents/index.js
  src/pages/PsychologistProfile/index.js
  src/pages/PsychologistProfile/styles.css
  src/pages/PsychologistSchedule/index.js
  src/pages/UserEvents/index.js
  src/pages/UserMain/index.js
  src/pages/UserProfile/index.js
  src/pages/UserProfile/styles.css
Labels: bug

#38 Fix/designer fixes
  .codeclimate.yml
  .eslintrc
  package-lock.json
  package.json
  src/assets/images/caio_colaborador.jpeg
  src/assets/images/tiringa_colaborador.jpg
  src/assets/styles/Calendar.css
  src/assets/styles/NavBar.css
  src/assets/styles/SideBar.css
  src/pages/AdminMain/styles.css
  src/pages/Landing/index.js
  src/pages/Landing/styles.css
  src/pages/LandingLogin/index.js
  src/pages/LandingLogin/styles.css
  src/pages/LandingSignUp/index.js
  src/pages/LandingSignUp/styles.css
  src/pages/NewSession/styles.css
  src/pages/PatientList/styles.css
  src/pages/PatientRecord/index.js
  src/pages/PatientRecord/styles.css
  src/pages/PsychologistCalendar/index.js
  src/pages/PsychologistCalendar/styles.css
  src/pages/PsychologistCreate/index.js
  src/pages/PsychologistCreate/styles.css
  src/pages/PsychologistEvents/index.js
  src/pages/PsychologistEvents/styles.css
  src/pages/PsychologistList/styles.css
  src/pages/PsychologistProfile/index.js
  src/pages/PsychologistSchedule/index.js
  src/pages/PsychologistSchedule/styles.css
  src/pages/UserEvents/styles.css
  src/pages/UserMain/index.js
  src/pages/UserMain/styles.css
  src/pages/UserProfile/index.js
  src/pages/UserProfile/styles.css
  src/pages/UserSchedule/styles.css
  src/tests/WaitingList.test.js
  yarn.lock
Labels: enhancement

#42 Fix/correcoes diversas
  src/components/NavBar.js
  src/components/SideBar.js
  src/pages/Landing/index.js
  src/pages/NewSession/index.js
  src/pages/PatientList/index.js
  src/pages/PatientRecord/index.js
  src/pages/PsychologistCalendar/index.js
  src/pages/PsychologistEvents/index.js
  src/pages/PsychologistProfile/index.js
  src/pages/PsychologistSchedule/index.js
  src/pages/UserMain/index.js
  src/pages/UserProfile/index.js
Labels: bug

#35 WIP: Teste end to end (ponta a ponta)
  .codeclimate.yml
  .github/workflows/teste2e.yml
  .nyc_output/out.json
  cypress.json
  cypress/fixtures/psychologist_list.json
  cypress/fixtures/psychologist_list_add.json
  cypress/fixtures/psychologist_list_remove.json
  cypress/integration/admin/login.spec.js
  cypress/integration/admin/manager_psychologists.spec.js
  cypress/integration/patient/changePassword.spec.js
  cypress/integration/patient/login.spec.js
  cypress/integration/patient/signup.spec.js
  cypress/integration/professional/general_management.spec.js
  cypress/integration/professional/login.spec.js
  cypress/integration/professional/psychologist_manager.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  debug.log
  package.json
  src/pages/ChangePassword/index.js
  src/pages/ChangePassword/styles.css
  src/pages/Home/index.js
  src/pages/LandingLogin/index.js
  src/pages/LoginAdmin/index.js
  src/pages/PatientRecord/index.js
  src/routes.js
  src/services/api.js
  yarn.lock
Labels: help wanted

#43 Waiting-List Page
  src/components/NavBar.js
  src/pages/WaitingList/index.js
  src/pages/WaitingList/styles.css
  src/routes.js
Labels: enhancement
